server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

info:
  app.name: microcloud
  company.name: www.chenbin113.top
  build.artifactId: @project.artifactId@
  build.version: @project.version@


zuul:
  prefix: /chenbin113
  ignored-services: microservicecloud-dept #单个微服务路径
  #ignored-services: "*" #多个微服务路径
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**